stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:
  stage: build
  image: gradle:6.8-jdk11
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/

test-job:
  stage: test
  image: gradle:6.8-jdk11
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/test-results/
      - build/reports/tests/
  allow_failure: false
